- name: checking data types
  hosts: localhost
  vars: 
    Name: jeevitha #its a key value
    Skills: # Skills is a list type
    - DevOps
    - Shell
    - Ansible
    - Linux
    Experience: # its map type i have key value pair
      DevOps: 8
      AWS: 6
      Docker: 4
    Trainer: true #type is boolean
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "Name: {{Name}}"

  - name: Print list
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"

  - name: print map
    ansible.builtin.debug:
      msg: "Experiance: {{Experiance}}"

  - name: print boolean
    ansible.builtin.debug:
      msg: "is he trainer:{{Trainer}}"           

