- name: loops
  hosts: localhost
  tasks:
  - name: print persons
    ansible.buitin.debug:
      msg: "Hello {{item}}" # item is default keyword
    loop:
    - ramesh
    - suresh
    - ram
    - raheem  