- name: checking data types
  hosts: localhost
  vars:
    NAME: jeevitha
    Skills: #list type
    - Devops
    - shell
    - linux
    - ansible
    Experiance: # map type
      aws: 1  
    Trainer: true # boolean
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "Name: {{NAME}}"
  - name: print list
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"
  - name: print map
    ansible.builtin.debug:
      msg: "Experiance: {{Experiance}}"  
  - name: print boolean
    ansible.builtin.debug:
      msg: "Trainer: {{Trainer}}"              