- name: loops
  hosts: localhost
  tasks:
  - name: print persons
    ansible.builtin.debug:
      msg: "Hai {{ item }}" # it's s default keyword
    loop:
    - ramesh
    - suresh
    - jeevitha
    - rama 